import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/layout/navbar/navbar";

const montserrat = Montserrat({
  variable: "--font-mont",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable}  bg-light w-full min-h-screen`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
